-- ======================================================
-- Apex Network
-- Rewarded Ad Mining Boost x3 for 24 hours
--
-- Design:
--   - One active boost at a time
--   - Boost duration: exactly 24 hours
--   - No stacking / no extension while active
--   - x3 applies to BASE mining rate only
--   - Referral bonus (+5% of base per active friend)
--     remains unchanged
--   - Every boost interval is stored so mining claims
--     remain accurate even if a user does not claim for
--     multiple days and activates more than one boost
--     over that period
-- ======================================================


-- ======================================================
-- 1. Current boost state on users
-- ======================================================

alter table public.users
  add column if not exists
    mining_boost_started_at timestamptz null;

alter table public.users
  add column if not exists
    mining_boost_until timestamptz null;

alter table public.users
  add column if not exists
    mining_boost_count integer not null default 0;


-- ======================================================
-- 2. Boost history
--
-- The history is necessary for exact mining accounting.
--
-- Example:
--   normal mining -> x3 boost -> normal mining -> x3 boost
--
-- If the user waits several days before Claim, the RPC
-- can still calculate each boosted interval correctly.
-- ======================================================

create table if not exists public.mining_boost_events (
  id bigint
    generated by default as identity
    primary key,

  telegram_id text not null,

  started_at timestamptz not null,

  ends_at timestamptz not null,

  created_at timestamptz
    not null
    default now(),

  constraint
    mining_boost_events_valid_window
    check (
      ends_at >
      started_at
    )
);


create index if not exists
  mining_boost_events_user_window_idx
on public.mining_boost_events (
  telegram_id,
  started_at,
  ends_at
);


alter table public.mining_boost_events
  enable row level security;


revoke all
  on table public.mining_boost_events
  from anon;

revoke all
  on table public.mining_boost_events
  from authenticated;


-- ======================================================
-- 3. Activate x3 boost RPC
--
-- Server-side rules:
--   - Telegram user must already exist
--   - Existing active boost blocks a new activation
--   - New boost lasts exactly 24 hours
--   - Activation is atomic under a users-row lock
-- ======================================================

create or replace function public.apex_activate_mining_boost(
  p_telegram_id bigint
)
returns table (
  success boolean,
  mining_boost_started_at timestamptz,
  mining_boost_until timestamptz,
  mining_boost_count integer,
  retry_after integer,
  error_code text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();

  v_started_at timestamptz;
  v_until timestamptz;
  v_count integer := 0;

  v_retry_after integer := 0;
begin
  perform set_config(
    'TimeZone',
    'UTC',
    true
  );


  -- Lock the user row so two simultaneous requests
  -- cannot create two boosts.
  select
    u.mining_boost_started_at,
    u.mining_boost_until,
    coalesce(
      u.mining_boost_count,
      0
    )::integer

  into
    v_started_at,
    v_until,
    v_count

  from public.users as u

  where
    u.telegram_id =
      p_telegram_id::text

  for update;


  if not found then
    return query
    select
      false,
      null::timestamptz,
      null::timestamptz,
      0::integer,
      0::integer,
      'USER_NOT_FOUND'::text;

    return;
  end if;


  -- Active boost = no stacking and no extension.
  if
    v_until is not null
    and
    v_until > v_now
  then
    v_retry_after :=
      greatest(
        1,
        ceil(
          extract(
            epoch from (
              v_until -
              v_now
            )
          )
        )::integer
      );

    return query
    select
      false,
      v_started_at,
      v_until,
      v_count,
      v_retry_after,
      'BOOST_ACTIVE'::text;

    return;
  end if;


  v_started_at :=
    v_now;

  v_until :=
    v_now +
    interval '24 hours';


  -- Keep an immutable interval for exact future
  -- mining calculations.
  insert into public.mining_boost_events (
    telegram_id,
    started_at,
    ends_at
  )
  values (
    p_telegram_id::text,
    v_started_at,
    v_until
  );


  update public.users as u

  set
    mining_boost_started_at =
      v_started_at,

    mining_boost_until =
      v_until,

    mining_boost_count =
      coalesce(
        u.mining_boost_count,
        0
      ) + 1

  where
    u.telegram_id =
      p_telegram_id::text

  returning
    u.mining_boost_count::integer

  into
    v_count;


  return query
  select
    true,
    v_started_at,
    v_until,
    v_count,
    0::integer,
    null::text;
end;
$$;


revoke execute
  on function
    public.apex_activate_mining_boost(bigint)
  from public;

revoke execute
  on function
    public.apex_activate_mining_boost(bigint)
  from anon;

revoke execute
  on function
    public.apex_activate_mining_boost(bigint)
  from authenticated;

grant execute
  on function
    public.apex_activate_mining_boost(bigint)
  to service_role;


-- ======================================================
-- 4. Mining Claim RPC with exact boost accounting
--
-- Existing public return schema is preserved so the
-- existing API route remains compatible.
--
-- Existing rules preserved:
--   - Claim cooldown = 12 hours
--   - Active referral = claimed in last 24 hours
--   - Referral boost = +5% of base rate per active friend
--
-- New rule:
--   - x3 applies to BASE rate only during recorded
--     boost intervals.
-- ======================================================

create or replace function public.apex_mining_claim(
  p_telegram_id bigint
)
returns table (
  success boolean,
  balance numeric,
  claimed numeric,
  mining_rate numeric,
  base_mining_rate numeric,
  active_friends bigint,
  last_claim timestamptz,
  cooldown integer,
  retry_after integer,
  error_code text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_balance numeric;
  v_base_rate numeric;
  v_last_claim timestamptz;
  v_now timestamptz := now();

  v_elapsed_seconds numeric;
  v_active_friends bigint := 0;

  v_referral_rate numeric := 0;
  v_normal_rate numeric := 0;
  v_boosted_rate numeric := 0;
  v_total_rate numeric := 0;

  v_boost_started_at timestamptz;
  v_boost_until timestamptz;

  v_boosted_seconds numeric := 0;
  v_normal_seconds numeric := 0;

  v_claimed numeric;
  v_new_balance numeric;

  v_cooldown integer := 43200;
  v_retry_after integer := 0;
begin
  perform set_config(
    'TimeZone',
    'UTC',
    true
  );


  -- ====================================================
  -- PHASE 1
  -- Fast indexed cooldown pre-check.
  -- No row lock and no referral/boost calculations.
  -- ====================================================

  select
    coalesce(
      u.balance,
      0
    )::numeric,

    coalesce(
      u.mining_rate,
      0.00025
    )::numeric,

    u.last_claim

  into
    v_balance,
    v_base_rate,
    v_last_claim

  from public.users as u

  where
    u.telegram_id =
      p_telegram_id::text;


  if not found then
    return query
    select
      false,
      0::numeric,
      0::numeric,
      0::numeric,
      0::numeric,
      0::bigint,
      null::timestamptz,
      v_cooldown,
      0,
      'USER_NOT_FOUND'::text;

    return;
  end if;


  if v_last_claim is null then
    v_last_claim :=
      v_now;
  end if;


  v_elapsed_seconds :=
    greatest(
      0::numeric,
      extract(
        epoch from (
          v_now -
          v_last_claim
        )
      )
    );


  if
    v_elapsed_seconds <
    v_cooldown
  then
    v_retry_after :=
      ceil(
        v_cooldown -
        v_elapsed_seconds
      )::integer;

    return query
    select
      false,
      v_balance,
      0::numeric,
      v_base_rate,
      v_base_rate,
      0::bigint,
      v_last_claim,
      v_cooldown,
      v_retry_after,
      'COOLDOWN'::text;

    return;
  end if;


  -- ====================================================
  -- PHASE 2
  -- Authoritative row lock and re-read.
  -- ====================================================

  select
    coalesce(
      u.balance,
      0
    )::numeric,

    coalesce(
      u.mining_rate,
      0.00025
    )::numeric,

    u.last_claim,

    u.mining_boost_started_at,

    u.mining_boost_until

  into
    v_balance,
    v_base_rate,
    v_last_claim,
    v_boost_started_at,
    v_boost_until

  from public.users as u

  where
    u.telegram_id =
      p_telegram_id::text

  for update;


  if not found then
    return query
    select
      false,
      0::numeric,
      0::numeric,
      0::numeric,
      0::numeric,
      0::bigint,
      null::timestamptz,
      v_cooldown,
      0,
      'USER_NOT_FOUND'::text;

    return;
  end if;


  if v_last_claim is null then
    v_last_claim :=
      v_now;
  end if;


  v_elapsed_seconds :=
    greatest(
      0::numeric,
      extract(
        epoch from (
          v_now -
          v_last_claim
        )
      )
    );


  -- Required re-check while locked.
  if
    v_elapsed_seconds <
    v_cooldown
  then
    v_retry_after :=
      ceil(
        v_cooldown -
        v_elapsed_seconds
      )::integer;

    return query
    select
      false,
      v_balance,
      0::numeric,
      v_base_rate,
      v_base_rate,
      0::bigint,
      v_last_claim,
      v_cooldown,
      v_retry_after,
      'COOLDOWN'::text;

    return;
  end if;


  -- ====================================================
  -- Active referrals
  -- Existing +5% logic remains unchanged.
  -- ====================================================

  select
    count(*)

  into
    v_active_friends

  from public.users as f

  where
    f.referred_by =
      p_telegram_id::text

    and

    f.last_claim >=
      v_now -
      interval '24 hours';


  v_referral_rate :=
    v_active_friends *
    (
      v_base_rate *
      0.05
    );


  v_normal_rate :=
    v_base_rate +
    v_referral_rate;


  -- x3 only the base rate.
  v_boosted_rate :=
    (
      v_base_rate *
      3
    ) +
    v_referral_rate;


  -- Current speed returned to the existing API/frontend.
  if
    v_boost_started_at is not null
    and
    v_boost_until is not null
    and
    v_boost_started_at <= v_now
    and
    v_boost_until > v_now
  then
    v_total_rate :=
      v_boosted_rate;
  else
    v_total_rate :=
      v_normal_rate;
  end if;


  -- ====================================================
  -- Exact boosted time since the previous Claim.
  --
  -- Sum the overlap between:
  --   [last_claim, now]
  -- and every recorded:
  --   [boost_started, boost_ends]
  --
  -- Boost periods never overlap because activation is
  -- protected by the locked users row.
  -- ====================================================

  select
    coalesce(
      sum(
        greatest(
          0::numeric,
          extract(
            epoch from (
              least(
                v_now,
                e.ends_at
              ) -
              greatest(
                v_last_claim,
                e.started_at
              )
            )
          )
        )
      ),
      0::numeric
    )::numeric

  into
    v_boosted_seconds

  from public.mining_boost_events as e

  where
    e.telegram_id =
      p_telegram_id::text

    and

    e.ends_at >
      v_last_claim

    and

    e.started_at <
      v_now;


  v_boosted_seconds :=
    least(
      v_elapsed_seconds,
      greatest(
        0::numeric,
        v_boosted_seconds
      )
    );


  v_normal_seconds :=
    greatest(
      0::numeric,
      v_elapsed_seconds -
      v_boosted_seconds
    );


  -- ====================================================
  -- Reward:
  --
  -- normal seconds × normal rate
  -- +
  -- boosted seconds × boosted rate
  -- ====================================================

  v_claimed :=
    (
      v_normal_seconds *
      v_normal_rate
    ) +
    (
      v_boosted_seconds *
      v_boosted_rate
    );


  v_new_balance :=
    v_balance +
    v_claimed;


  update public.users as u

  set
    balance =
      v_new_balance,

    last_claim =
      v_now

  where
    u.telegram_id =
      p_telegram_id::text;


  -- Any boost interval that already ended is now fully
  -- accounted for because last_claim becomes v_now.
  --
  -- Active boost events are retained for the remaining
  -- future boosted seconds.
  delete from public.mining_boost_events as e

  where
    e.telegram_id =
      p_telegram_id::text

    and

    e.ends_at <=
      v_now;


  return query
  select
    true,
    v_new_balance,
    v_claimed,
    v_total_rate,
    v_base_rate,
    v_active_friends,
    v_now,
    v_cooldown,
    0,
    null::text;
end;
$$;


revoke execute
  on function
    public.apex_mining_claim(bigint)
  from public;

revoke execute
  on function
    public.apex_mining_claim(bigint)
  from anon;

revoke execute
  on function
    public.apex_mining_claim(bigint)
  from authenticated;

grant execute
  on function
    public.apex_mining_claim(bigint)
  to service_role;

